Personal Finance Manager/Controllers/BudgetController.cs
using Microsoft.AspNetCore.Mvc;
using Personal_Finance_Manager.Data.Repositories;
using Personal_Finance_Manager.Models;
using System.Security.Claims;
using Personal_Finance_Manager.ViewModels;

namespace Personal_Finance_Manager.Controllers
{
    public class BudgetController : Controller
    {
        private IBudgetRepository _budgetRepository;
        private string _userId { get { return User.FindFirstValue(ClaimTypes.NameIdentifier); } }

        public BudgetController(IBudgetRepository budgetRepository)
        {
            _budgetRepository = budgetRepository;
        }


        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var budgets = await _budgetRepository.GetBudgetsByUser(_userId);

            foreach (var budget in budgets)
            {
                budget.TotalSpent = await _budgetRepository.GetTotalSpent(budget.Id);
            }

            return View(budgets);
        }


        [HttpGet]
        public async Task<IActionResult> CreateBudget()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateBudget(CreateBudgetViewModel budgetVM)
        {
            var budget = new Budget()
            {
                OwnerUserId = _userId,
                Name = budgetVM.Name,
                Balance = budgetVM.Balance
            };

            await _budgetRepository.CreateBudget(budget);

            return View();
        }

 
        [HttpPost]
        public async Task<IActionResult> DeleteBudget(int budgetId)
        {
            await _budgetRepository.DeleteBudget(budgetId, _userId);

            return RedirectToAction(nameof(Index));
        }


        [HttpGet]
        public async Task<IActionResult> GetBudgetEntries(int budgetId)
        {
            var budget = await _budgetRepository.GetBudgetById(budgetId, _userId);

            budget.TotalSpent = await _budgetRepository.GetTotalSpent(budgetId);

            var entries = await _budgetRepository.GetBudgetEntriesByBudget(budgetId, _userId);

            var vm = new BudgetEntryViewModel
            {
                Budget = budget,
                Entries = entries.ToList()
            };

            return View(vm);
        }


        [HttpGet]
        public async Task<IActionResult> CreateBudgetEntry(int budgetId)
        {
            var budget = await _budgetRepository.GetBudgetById(budgetId, _userId);

            var entryVM = new CreateBudgetEntryViewModel()
            {
                BudgetId = budgetId,
                BudgetName = budget.Name
            };

            return View(entryVM);
        }

        [HttpPost]
        public async Task<IActionResult> CreateBudgetEntry(CreateBudgetEntryViewModel entryVM)
        {
            var entry = new BudgetEntry()
            {
                BudgetId = entryVM.BudgetId,
                OwnerUserId = _userId,
                Name = entryVM.Name,
                Amount = entryVM.Amount
            };

            await _budgetRepository.CreateBudgetEntry(entry);

            return RedirectToAction(nameof(GetBudgetEntries), new { budgetId = entryVM.BudgetId });
        }

      
        [HttpPost]
        public async Task<IActionResult> DeleteBudgetEntry(int budgetEntryId, int budgetId)
        {
            await _budgetRepository.DeleteBudgetEntry(budgetEntryId, _userId);

            return RedirectToAction(nameof(GetBudgetEntries), new { budgetId = budgetId });
        }
    }
}

Personal Finance Manager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Personal_Finance_Manager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Personal_Finance_Manager.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Personal_Finance_Manager</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Index">Accounts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Budget" asp-action="Index">Budgets</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Personal_Finance_Manager 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>